### ISSUE TITLE
Link without redirect fails

### ISSUE THREAD

**Issue by SleeplessByte** [BranchMetrics/Web-SDK#74]
A short link that was created works as follows:

- The link: http://ever.gi/l/5sV8r8k05e
- Redirects to: https://evergive.com/invitation#r:136968003693614260
- Use the web SDK to get the branch data
  - If branch data is valid, redirect (https://evergive.com/community/paystik)
  - If branch data is null, redirect (https://bnc.lt/l/1xPxnKE--k)

If you follow the first link, everything works as expected. If you follow the second link it doesn't. For some reason the `Web-SDK` doesn't use the `#r:redirectedlinkid` if there was no redirect.

**Comment by derrickstaten** [comment]
Hi @SleeplessByte, when you say "follow the second link", do you mean just clicking the URL https://evergive.com/invitation#r:136968003693614260 without clicking on a Branch link?

If so, the reason this doesn't work is because there is no outstanding click on our backend. From our point of view, you could send up https://evergive.com/invitation#r:1234 -- that's the same as https://evergive.com/invitation#r:136968003693614260.

Does this make sense? We don't have an outstanding Branch link click when you click https://evergive.com/invitation#r:136968003693614260, so when the Web SDK initializes and calls out to our servers, we return nothing.

Hopefully I've understood you properly.

**Comment by SleeplessByte** [comment]
Are you saying that after a click the SDK only returns data once, and not on consecutive calls?

**Comment by derrickstaten** [comment]
For each link click, the SDK returns data once, yes -- on the session immediately following the link click.

**Comment by SleeplessByte** [comment]
That makes sense, thanks for clearing that up.

**Comment by derrickstaten** [comment]
No problem -- questions are always welcome. You can also ping us at support@branchmetrics.io, as I watch that a bit more frequently

**Comment by SleeplessByte** [comment]
Myes, but this is public record and indexed by Google :)
